git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

services:
  'hub.nucleoo.com': 'gitlab:hub.nucleoo.com'
  'bitbucket.mova.indra.es': 'bitbucketServer:bitbucket.mova.indra.es'

os:
  editPreset: 'nvim-remote'
