git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

services:
  'hub.nucleoo.com': 'gitlab:hub.nucleoo.com'
  'bitbucket.mova.indra.es': 'bitbucket:bitbucket.mova.indra.es'

os:
  editPreset: 'nvim-remote'

gui:
  # https://github.com/catppuccin/lazygit/blob/main/themes/frappe/flamingo.yml
  theme:
    activeBorderColor:
      - '#eebebe'
      - bold
    inactiveBorderColor:
      - '#a5adce'
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#414559'
    cherryPickedCommitBgColor:
      - '#51576d'
    cherryPickedCommitFgColor:
      - '#eebebe'
    unstagedChangesColor:
      - '#e78284'
    defaultFgColor:
      - '#c6d0f5'
    searchingActiveBorderColor:
      - '#e5c890'

  authorColors:
    '*': '#babbf1'
