# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F5ECE9
background         #2D3131
cursor             #A09DA9

active_tab_foreground     #2D3131
active_tab_background     #F5ECE9
inactive_tab_foreground   #F5ECE9
inactive_tab_background   #2D3131

active_border_color   #F5ECE9
inactive_border_color #2D3131
bell_border_color     #192629

color0      #525556
color1		#192629
color2		#393A4F
color3		#4E4F3E
color4		#6B6D82
color5		#9C8E4E
color6		#AA988F
color7		#E8DCD7
color8		#A29A96
color9		#213336
color10		#4C4D69
color11		#686953
color12		#8F92AE
color13		#D0BE68
color14		#E2CABF
color15		#E8DCD7
