---@type LazyConfig
return {
  -- You exceeded your current quota :shrug:
  --   you need to pay
  -- {
  --   "jackMort/ChatGPT.nvim",
  --   event = "VeryLazy",
  --   commit = "62443c9eb261e641d20af143357b157e3f542bb5",
  --   config = function()
  --     require("chatgpt").setup({
  --       api_key_cmd = "pass show openai-nucleoo",
  --       -- api_host_cmd = "echo -n 'api.openai.com'",
  --     })
  --   end,
  --   dependencies = {
  --     "MunifTanjim/nui.nvim",
  --     "nvim-lua/plenary.nvim",
  --     "nvim-telescope/telescope.nvim",
  --   },
  -- },
}
